export const europeanCountries = [
    "Albania", 
    "Armenia", 
    "Austria",
    "Belarus", 
    "Belgium", 
    "Bosnia and Herzegovina", 
    "Bulgaria", 
    "Croatia", 
    "Cyprus", 
    "Czech Republic", 
    "Denmark", 
    "Estonia", 
    "Finland", 
    "France", 
    "Georgia", 
    "Germany", 
    "Greece", 
    "Hungary", 
    "Iceland", 
    "Ireland", 
    "Italy", 
    "Kosovo", 
    "Latvia", 
    "Lithuania", 
    "Luxembourg", 
    "Moldova", 
    "Montenegro", 
    "Netherlands", 
    "North Macedonia", 
    "Norway", 
    "Poland", 
    "Portugal", 
    "Romania", 
    "Serbia", 
    "Slovakia", 
    "Slovenia", 
    "Spain", 
    "Sweden", 
    "Switzerland", 
    "Turkey", 
    "Ukraine", 
    "United Kingdom", 
  ];
  