export const europeanCountries = [
    "Albania", 
    "Armenia", 
    "Austria",
    "Belarus", 
    "Belgium", 
    "Bosnia and Herzegovina", 
    "Bulgaria", 
    "Croatia", 
    "Cyprus", 
    "Czech Republic", 
    "Denmark", 
    "Estonia", 
    "Finland", 
    "France", 
    "Georgia", 
    "Germany", 
    "Greece", 
    "Hungary", 
    "Iceland", 
    "Ireland", 
    "Italy", 
    "Kosovo", 
    "Latvia", 
    "Lithuania", 
    "Luxembourg", 
    "Moldova", 
    "Montenegro", 
    "Netherlands", 
    "North Macedonia", 
    "Norway", 
    "Poland", 
    "Portugal", 
    "Romania", 
    "Serbia", 
    "Slovakia", 
    "Slovenia", 
    "Spain", 
    "Sweden", 
    "Switzerland", 
    "Turkey", 
    "Ukraine", 
    "United Kingdom", 
  ];

  export const asianCountries = [
    "Afghanistan",
    "Armenia",
    "Azerbaijan",
    "Bahrain",
    "Bangladesh",
    "Bhutan",
    "Brunei",
    "Cambodia",
    "China",
    "Cyprus",
    "Georgia",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Israel",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Lebanon",
    "Malaysia",
    "Mongolia",
    "Burma",
    "Nepal",
    "North Korea",
    "Oman",
    "Pakistan",
    "Palestine",
    "Philippines",
    "Qatar",
    "Saudi Arabia",
    "Singapore",
    "South Korea",
    "Sri Lanka",
    "Syria",
    "Tajikistan",
    "Thailand",
    "Timor-Leste",
    "Turkey",
    "Turkmenistan",
    "United Arab Emirates",
    "Uzbekistan",
    "Vietnam",
    "Yemen"
  ]



  export const southAmericanCountries = [
    "Argentina",
    "Bolivia",
    "Brazil",
    "Chile",
    "Colombia",
    "Ecuador",
    "Guyana",
    "Paraguay",
    "Peru",
    "Suriname",
    "Uruguay",
    "Venezuela"
];
  